- name: Create docker network
      shell: "sudo docker network create --driver=bridge --subnet={{subnet}} {{network_name}} || true" #adding '|| true' will not return error while running the script again
      become: true

- name: pull image
  community.docker.docker_image:
    name: httpd
    source: pull
    tag: latest

- name: webroot present
  ansible.builtin.file:
    path: "{{webroot}}"
    state: directory

- name: run httpd container
  community.docker.docker_container:
    name: "{{container_name}}"
    image: httpd
    state: started
    detach: true
    restart: yes
    restart_policy: always
    exposed_ports:
      - 80
    ports:
      - 80:80
    volumes: "{{webroot}}:/usr/local/apache2/htdocs/"
    networks:
      - name: "{{network_name}}"