- name: Deploy Apache container
  hosts: localhost
  become: yes
  vars:
    container_name: my-apache-server
    network_name: shared
    subnet: 172.168.10.0/30
    host_port: 80

  tasks:
    - name: Check if docker is installed or not
      command: docker --version
      register: docker_valid
      ignore_errors: yes

    - name: Print variable values
      debug:
        var: docker_valid #contains a json object

    - name: Install Docker pre-requisites
      include_tasks: docker-install.yaml
      when: docker_valid.failed #returns a boolean value

    # Below task creates a custom network with the mentioned subnet. The custom network is named as 'shared'
    - name: Create docker network
      shell: "sudo docker network create --driver=bridge --subnet={{subnet}} {{network_name}} || true" #adding '|| true' will not return error while running the script
      become: true

    # Below commands uses a Dockerfile to run apache container
    # --------------------------------------------------------
    # - name: Build Apache container
    #   shell: "sudo docker build -t apache-server ./Apache"
    #   become: true

    # - name: Run Apache container
    #   shell: "sudo docker run -d -p 80:80 --name {{container_name}} apache-server tail -f /dev/null"
    #   become: true
    # ---------------------------------------------------------

    - name: Run Apache container
      shell: 'sudo docker run -d --name {{container_name}} -p {{host_port}}:80 -v ./website/:/usr/local/apache2/htdocs/ httpd:2.4'
      become: true

    - name: Connect Apache to the created network
      shell: "sudo docker network connect {{network_name}} {{container_name}}"

    - name: Restart the container every time the system reboots
      shell: "sudo docker update --restart=always {{container_name}}"