---
- name: Deploy Apache container
  hosts: apache
  become: yes
  vars:
    container_name: my-apache-server
    network_name: shared
    subnet: 172.168.10.0/30
    host_port: 80
    webroot: "./website/"

  tasks:
    - name: Check if docker is installed or not
      command: docker --version
      register: docker_valid
      ignore_errors: yes

    - name: Print variable values
      debug:
        var: docker_valid #contains a json object

    - name: Install Docker pre-requisites
      include_tasks: docker-install.yaml
      when: docker_valid.failed #returns a boolean value

    - name: Install Apache docker container
      include_tasks: apache-install.yaml
